import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Bundle CSS files from styles folder
function bundleCSS() {
	const stylesDir = 'styles';
	const cssFiles = [
		'searchModal.css',
	];
	
	let bundledCSS = '/* Bookshelf Plugin Styles */\n\n';
	
	cssFiles.forEach(file => {
		try {
			const content = readFileSync(join(stylesDir, file), 'utf-8');
			bundledCSS += `/* ${file} */\n${content}\n\n`;
		} catch (error) {
			console.warn(`Warning: Could not read ${file}:`, error);
		}
	});
	
	writeFileSync('styles.css', bundledCSS);
	console.log('CSS bundled to styles.css');
}

// Bundle CSS before building
bundleCSS();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
